#ifndef PTHREAD_DEFINES_
#define PTHREAD_DEFINES_

#define WORKER_THREAD_PRIORITY (60)
#define WORKER_THREAD_CPU_AFFINITY (3)
#define WORKER_THREAD_STACK_SIZE (PTHREAD_STACK_MIN

#define PIGPIO_THREAD_PRIORITY (70)
#define PIGPIO_THREAD_CPU_AFFINITY (3)
//#define PIGPIO_THREAD_STACK_SIZE (PTHREAD_STACK_MIN

#endif // PTHREAD_DEFINES_